package_rename_config:
  android:
    app_name: "E Commerce"
    package_name: "com.youtube.ecommerce"
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "E Commerce"
    bundle_name: # (String) The bundle name of the ios app
    package_name: "com.youtube.ecommerce"